Vagrant.configure("2") do |config|

	(1..3).each do |i|

		config.vm.define "node#{i}" do |node|

		# 设置虚拟机的Box
		node.vm.box = "ubuntu1604"

		# 设置虚拟机的主机名
		node.vm.hostname="node#{i}"

		# set username
		node.ssh.username="ubuntu"

		# 设置虚拟机的IP
		node.vm.network "private_network", ip: "192.168.100.10#{i}"

		# 设置主机与虚拟机的共享目录
		# node.vm.synced_folder "~/Desktop/share", "/home/vagrant/share"

		# VirtaulBox相关配置
		node.vm.provider "virtualbox" do |v|

			# 设置虚拟机的名称
			v.name = "node#{i}"

			# 设置虚拟机的内存大小  
			v.memory = 2048

			# 设置虚拟机的CPU个数
			v.cpus = 1
		end
  
		# 使用shell脚本进行软件安装和配置
		node.vm.provision "shell", inline: <<-SHELL

			# 安装docker 1.11.0
			sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
			curl -sSL https://get.daocloud.io/docker | sh
			usermod -aG docker ubuntu
			
		SHELL

		end
	end
end